### ISSUE TITLE
在执行完python main_openai.py --scenario_name simple_tag后遇到的问题

### ISSUE THREAD

**Issue by glong1997** [DKuan/MADDPG_torch#1]
=============================
=1 Env simple_tag is right ...
=============================
=2 The 4 agents are inited ...
=============================
=3 starting iterations ...
=============================
=start training ...
=time:1912_032119 step:130000        save  episode reward:12.616 agents mean reward:[6.48, 6.48, 6.48, -6.83]]]
Traceback (most recent call last):
  File "main_openai.py", line 246, in <module>
    train(arglist)
  File "main_openai.py", line 228, in train
    actors_cur, actors_tar, critics_cur, critics_tar, optimizers_a, optimizers_c)
  File "main_openai.py", line 141, in agents_train
    os.mkdir(model_file_dir)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'models\\simple_tag_1912_032119_130000'

**Comment by DKuan** [comment]
在MADDPG_torch的目录下新建一个 models文件夹

**Comment by glong1997** [comment]
谢谢！这个问题解决了。还有一个问题，在运行enjoy_split.py后出现的状况：
C:\Users\Long\Anaconda3\python.exe C:/Users/Long/Desktop/MADDPG_torch-master/MADDPG_torch-master/enjoy_split.py
Traceback (most recent call last):
  File "C:/Users/Long/Desktop/MADDPG_torch-master/MADDPG_torch-master/enjoy_split.py", line 85, in <module>
    enjoy(arglist)
  File "C:/Users/Long/Desktop/MADDPG_torch-master/MADDPG_torch-master/enjoy_split.py", line 47, in enjoy
    actors_tar = get_trainers(env, obs_shape_n, arglist.action_size, arglist)
AttributeError: 'Namespace' object has no attribute 'action_size'

**Comment by DKuan** [comment]
action_size的函数参数可以删去，load训练好的模型时不需要这个参数了，我当时是在新建的工程中测试的，这个错误没有注意到，我更新一下这个文件。

**Comment by glong1997** [comment]
删掉之后再运行变成这样了。。请教一下是什么原因？（我刚刚进入这个方向，很多东西还不太懂。谢谢你的回答）
C:\Users\Long\Anaconda3\python.exe C:/Users/Long/Desktop/MADDPG_torch-master/MADDPG_torch-master/enjoy_split.py
[array([-0.95301398,  0.75661673, -1.02676216,  1.53326611,  0.62013493,
Traceback (most recent call last):
        0.26346927, -0.41382679, -0.26071585]), array([-1.57314891,  0.49314746, -1.57314891,  0.49314746, -1.64689709,
        1.26979684, -0.62013493, -0.26346927, -1.03396172, -0.52418513]), array([-0.53918718,  1.01733258, -0.53918718,  1.01733258, -0.61293537,
        1.79398197,  0.41382679,  0.26071585,  1.03396172,  0.52418513])]
  File "C:/Users/Long/Desktop/MADDPG_torch-master/MADDPG_torch-master/enjoy_split.py", line 85, in <module>
    enjoy(arglist)
  File "C:/Users/Long/Desktop/MADDPG_torch-master/MADDPG_torch-master/enjoy_split.py", line 68, in enjoy
    new_obs_n, rew_n, done_n, info_n = env.step(action_n)
  File "C:\Users\Long\Anaconda3\lib\site-packages\multiagent\environment.py", line 88, in step
    self._set_action(action_n[i], agent, self.action_space[i])
IndexError: list index out of range

**Comment by DKuan** [comment]
我更新了enjoy_split.py文件，你用我刚更新的那个试一下。
